apiVersion: v1
kind: Service
metadata:
  name: pythonpocdocker-service
spec:
  selector:
    app: pythonpocdocker
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonpocdocker
spec:
  selector:
    matchLabels:
      app: pythonpocdocker
  replicas: 1
  template:
    metadata:
      labels:
        app: pythonpocdocker
    spec:
      containers:
      - name: pythonpocdocker
        image: karthikrallapalli/pythonpocdocker
        ports:
        - containerPort: 5000
